server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location = /revdash {
        return 301 https://revdashapp.com;
    }

    location ^~ /revdash/ {
        return 301 https://revdashapp.com;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
