import { Link } from "react-router-dom";

const sections = [
	{
		heading: null,
		body: `This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\nWe use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.`,
	},
	{
		heading: "Interpretation and Definitions",
		subheading: "Interpretation",
		body: `The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.`,
	},
	{
		heading: null,
		subheading: "Definitions",
		body: null,
		list: [
			{ term: "Account", def: "means a unique account created for You to access our Service or parts of our Service." },
			{ term: "Affiliate", def: `means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.` },
			{ term: "Application", def: "refers to RevDash, the software program provided by the Company." },
			{ term: "Company", def: `(referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to RevDash.` },
			{ term: "Country", def: "refers to: Philippines" },
			{ term: "Device", def: "means any device that can access the Service such as a computer, a cell phone or a digital tablet." },
			{ term: "Personal Data", def: `(or "Personal Information") is any information that relates to an identified or identifiable individual.` },
			{ term: "Service", def: "refers to the Application." },
			{ term: "Service Provider", def: "means any natural or legal person who processes the data on behalf of the Company." },
			{ term: "Usage Data", def: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself." },
			{ term: "You", def: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." },
		],
	},
	{
		heading: "Collecting and Using Your Personal Data",
		subheading: "Types of Data Collected",
		body: `Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\nWhile using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission, information regarding your location. You can enable or disable access to this information at any time, through Your Device settings.`,
	},
	{
		heading: null,
		subheading: "Use of Your Personal Data",
		body: "The Company may use Personal Data for the following purposes:",
		list: [
			{ term: "To provide and maintain our Service", def: "including to monitor the usage of our Service." },
			{ term: "To manage Your Account", def: "to manage Your registration as a user of the Service." },
			{ term: "For the performance of a contract", def: "the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service." },
			{ term: "To contact You", def: "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services." },
			{ term: "To manage Your requests", def: "To attend and manage Your requests to Us." },
			{ term: "For business transfers", def: "We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets." },
			{ term: "For other purposes", def: "We may use Your information for other purposes, such as data analysis, identifying usage trends, and to evaluate and improve our Service." },
		],
	},
	{
		heading: null,
		subheading: "Retention of Your Personal Data",
		body: `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We retain different categories of data for different periods:\n\n• User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure.\n• Application usage statistics: up to 24 months to understand feature adoption and service improvements.\n• Server logs: up to 24 months for security monitoring and troubleshooting.\n\nWhen retention periods expire, We securely delete or anonymize Personal Data.`,
	},
	{
		heading: null,
		subheading: "Transfer of Your Personal Data",
		body: `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.`,
	},
	{
		heading: null,
		subheading: "Delete Your Personal Data",
		body: `You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may contact Us to request access to, correct, or delete any Personal Data that You have provided to Us. Please note that We may need to retain certain information when we have a legal obligation or lawful basis to do so.`,
	},
	{
		heading: null,
		subheading: "Disclosure of Your Personal Data",
		body: `Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities. The Company may also disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, or protect the personal safety of Users of the Service or the public.`,
	},
	{
		heading: null,
		subheading: "Security of Your Personal Data",
		body: `The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.`,
	},
	{
		heading: "Children's Privacy",
		body: `Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.`,
	},
	{
		heading: "Links to Other Websites",
		body: `Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.`,
	},
	{
		heading: "Changes to this Privacy Policy",
		body: `We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.`,
	},
	{
		heading: "Contact Us",
		body: `If you have any questions about this Privacy Policy, you can contact us by email:`,
		contact: true,
	},
];

const RevDashPrivacy = () => {
	return (
		<div className="min-h-screen bg-primary text-white-100">
			<div className="max-w-3xl mx-auto px-6 pt-16 pb-24">
				<Link to="/revdash" className="text-secondary text-sm hover:text-white-100 transition-colors">
					← RevDash
				</Link>

				<h1 className="text-3xl font-bold tracking-tight text-white-100 mt-6 mb-2">Privacy Policy</h1>
				<p className="text-secondary text-sm mb-12">Last updated: April 27, 2026</p>

				<div className="space-y-10">
					{sections.map((section, i) => (
						<div key={i}>
							{section.heading && (
								<h2 className="text-white-100 text-xl font-semibold mb-3 border-b border-border-subtle pb-3">
									{section.heading}
								</h2>
							)}
							{section.subheading && (
								<h3 className="text-white-100 font-semibold text-[16px] mb-2">{section.subheading}</h3>
							)}
							{section.body && (
								<div className="text-secondary text-[15px] leading-relaxed whitespace-pre-line">
									{section.body}
								</div>
							)}
							{section.list && (
								<ul className="mt-3 space-y-2">
									{section.list.map((item) => (
										<li key={item.term} className="text-secondary text-[15px] leading-relaxed">
											<span className="text-white-100 font-medium">{item.term}</span> — {item.def}
										</li>
									))}
								</ul>
							)}
							{section.contact && (
								<a
									href="mailto:joshuavillartafigueroa@gmail.com"
									className="inline-block mt-3 bg-tertiary text-white-100 font-medium px-6 py-3 rounded-xl hover:opacity-80 transition-opacity"
								>
									joshuavillartafigueroa@gmail.com
								</a>
							)}
						</div>
					))}
				</div>
			</div>
		</div>
	);
};

export default RevDashPrivacy;
